const express = require('express');
const router = express.Router();
const orderController = require('../controllers/orderController');
router.get('/', orderController.getAllOrders);
router.get('/:id', orderController.getOrder);
router.post('/', orderController.createOrder);
router.put('/:id', orderController.updateOrder);
router.patch('/:id', orderController.updateOrderStatus);
router.delete('/:id', orderController.deleteOrder);
router.get('/search', orderController.searchOrders);
module.exports = router;
